const tr = {
        "lang": "tr",
        "home": "ANA SAYFA",
        "about": "HAKKIMDA",
        "skills": "YETENEKLERİM",
        "projects": "PROJELERİM",
        "contact": "İLETİŞİM",
        "downloadcv": "CV İndir",
        "viewproject": "Projeyi Göster",
        "knowmore": "Daha Fazla",
        "name": "Ad",
        "surname": "Soyad",
        "adress": "Adres",
        "hobby" : "Hobi",
        "age": "Yaş",
        "phone": "Telefon",
        "email": "EPosta",
        "title": "Başlık",
        "writemessage": "Mesajınızı Yazın...",
        "sendyourmessage": "Bana Mesaj Gönder",
        "sendmessagebutton": "Mesaj Gönder"
    };
    const en = {
        "lang": "en",
        "home": "HOME",
        "about": "ABOUT",
        "skills": "SKİLLS",
        "projects": "PROJECTS",
        "contact": "CONTACT",
        "downloadcv": "Download CV",
        "viewproject": "View Project",
        "knowmore": "Know More",
        "name": "Name",
        "surname": "Surname",
        "hobby" : "Hobby",
        "age": "Age",
        "phone": "Phone",
        "adress": "Adress",
        "email": "Email",
        "title": "Title",
        "writemessage": "Write Your Message",
        "sendyourmessage": "Send Your Message",
        "sendmessagebutton": "Send Message"
    };
    export const lang_config = {tr,en};